<a href="https://colab.research.google.com/github/sightes/MGMODELOSAVANZADOS-METODOSNUMERICOS/blob/main/%5BMG_MODELOS%5D_Metodos_numericos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Ejemplo creacion matrices

In [4]:
M<-matrix(c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


In [5]:
#Accedemos a la matriz elemento 1,2
M[1,2]

[1] 2

In [6]:
trunc(M)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

###Matriz identidad


In [8]:
N<-matrix(0,3,3)
N[row(N)==col(N)]<-1
print(N)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


In [9]:
is.matrix(N)

[1] TRUE

In [11]:
## que pasa que quisiese que la diagonal superior sea uno

N<-matrix(0,3,3)
N[row(N)<=col(N)]<-1
print(N)

     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    0    1    1
[3,]    0    0    1


In [12]:
## que pasa que quisiese que la diagonal superior sea uno

N<-matrix(0,3,3)
N[row(N)>=col(N)]<-1
print(N)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    1    1    0
[3,]    1    1    1


###Suma de matrices

In [13]:
M<-matrix(1:6,byrow=TRUE,nrow=3,ncol=2)
N<-matrix(7:12,nrow=3,ncol=2)
print(M)
print(N)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12


In [14]:
MS<-M+N
print(MS)

     [,1] [,2]
[1,]    8   12
[2,]   11   15
[3,]   14   18


In [15]:
MS<-M-N
print(MS)

     [,1] [,2]
[1,]   -6   -8
[2,]   -5   -7
[3,]   -4   -6


###Multiplicacion de matrices

In [18]:
# multiplicacion entre matrices
M<-matrix(1:6,byrow=TRUE,nrow=3,ncol=2)
N<-matrix(7:10,nrow=2,ncol=2)
MU<- M%*%N
print(MU)

     [,1] [,2]
[1,]   23   29
[2,]   53   67
[3,]   83  105


In [19]:
# Multiplicacion escalar
ME<- 2*M
print(ME)

     [,1] [,2]
[1,]    2    4
[2,]    6    8
[3,]   10   12
